'use client';
import {useEffect,useState} from 'react';
import {Ticket,Users,ScanLine,Settings,Plus,Music2,Copy,Printer,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import QRCode from 'qrcode';
type Guest={token:string,name:string,contact:string,method:string,amount:number,cancelled:number,entered_at:string|null,receipt:string|null,issued_by:string};
type EventData={name:string,date:string,venue:string,price:number,gate_key?:string,gate_open:number};
type Data={event:EventData,tickets:Guest[],team:{email:string}[],user:{email:string,isOwner:boolean}};
const initial:EventData={name:'Dandiya Night',date:'',venue:'',price:0,gate_open:0};
export async function call(action:Record<string,unknown>){const r=await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d}
export function when(date:string){return date?new Date(date).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})+' IST':'Date to be announced'}
export default function Dashboard(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[auth,setAuth]=useState(0),[busy,setBusy]=useState(false),[tab,setTab]=useState('tickets'),[open,setOpen]=useState(false),[newTicket,setNewTicket]=useState<Guest|null>(null),[form,setForm]=useState(initial),[paid,setPaid]=useState(false),[method,setMethod]=useState('Cash'),[requestId,setRequestId]=useState(''),[query,setQuery]=useState(''),[qr,setQr]=useState(''),[confirm,setConfirm]=useState<Guest|null>(null),[loginPass,setLoginPass]=useState('');
 async function refresh(quiet=false){if(!quiet)setLoading(true);try{const r=await fetch('/api/manage',{cache:'no-store'});const d:any=await r.json();if(!r.ok){setAuth(r.status);throw Error(d.error)}setData(d);setAuth(0);return d as Data}catch(e){if(!quiet)setError((e as Error).message);return null}finally{if(!quiet)setLoading(false)}}
 useEffect(()=>{void refresh().then(d=>{if(d)setForm({...d.event,price:d.event.price/100})})},[]);
 useEffect(()=>{if(!data)return;const timer=setInterval(()=>void refresh(true),10000);return()=>clearInterval(timer)},[!!data]);
 useEffect(()=>{if(!data?.event.gate_key)return;QRCode.toDataURL(JSON.stringify({site:location.origin,gate:data.event.gate_key}),{width:700,margin:2,errorCorrectionLevel:'M'}).then(setQr).catch(()=>setError('Could not create the gate QR. Reload and try again.'))},[data?.event.gate_key]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function start(){setError('');setNewTicket(null);setPaid(false);setMethod('Cash');setRequestId(crypto.randomUUID());setOpen(true)}
 function link(t:Guest){return location.origin+'/t/'+t.token}
 async function copy(t:Guest){try{await navigator.clipboard.writeText(link(t));setMessage('Ticket link copied. Send it to your guest.')}catch{setNewTicket(t);setOpen(true);setError('Copy was unavailable. Select and copy the link below.')}}
 async function doLogin(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:loginPass})});const d=await r.json();if(!r.ok)throw Error(d.error);setLoginPass('');await refresh()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 async function doLogout(){try{await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setData(null);setAuth(401)}catch{}}
 const tickets=data?.tickets||[],ev=data?.event||initial;const active=tickets.filter(t=>!t.cancelled);const checked=active.filter(t=>t.entered_at);const visible=tickets.filter(t=>(t.name+' '+t.contact+' '+t.token).toLowerCase().includes(query.toLowerCase()));
 return <main className="shell"><header><a className="brand" href="/"><Music2/> DANDIYA <span>NIGHT</span></a><div className="actions"><span className="pill">MANAGEMENT</span>{data&&<button className="muted" onClick={doLogout}>Sign out</button>}</div></header><div className="intro no-print"><div><p className="eyebrow">LET THE CELEBRATION BEGIN</p><h1>A little rhythm.<br/><em>A full house.</em></h1><p>Your tickets, your team, one unforgettable night.</p></div><div className="mini-ticket"><span>THE NIGHT IS YOURS</span><h2>{ev.name}</h2><div className="ticket-rule"/><p>ONE PERSON · ONE CELEBRATION</p><strong>ADMIT ONE</strong></div></div>
 {error&&<div role="alert" className="message no-print">{error}</div>}{message&&<div role="status" className="message success no-print">{message}</div>}
 {!data?<section className="panel"><h2>{loading?'Opening your guest list…':auth===403?'Access denied':'Welcome, organisers'}</h2><p>Enter the management password to continue.</p>{!loading&&<form className="form" onSubmit={doLogin} style={{maxWidth:340}}><label>Password<input type="password" value={loginPass} onChange={e=>setLoginPass(e.target.value)} required placeholder="Enter management password"/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in to manage'}</button></form>}{!loading&&auth!==401&&auth!==403&&<button className="secondary" onClick={()=>void refresh()}>Try again</button>}</section>:<Tabs value={tab} onValueChange={setTab}>
 <nav className="no-print"><TabsList className="h-auto w-full justify-start bg-transparent p-0"><TabsTrigger value="tickets"><Ticket/> Tickets</TabsTrigger><TabsTrigger value="gate"><ScanLine/> Gate</TabsTrigger><TabsTrigger value="team"><Users/> Team</TabsTrigger><TabsTrigger value="event"><Settings/> Event</TabsTrigger></TabsList></nav>
 <section className="stats"><div><span>Active tickets</span><strong>{active.length}</strong></div><div><span>Checked in</span><strong>{checked.length}</strong></div><div><span>Yet to arrive</span><strong>{active.length-checked.length}</strong></div></section>
 <TabsContent value="tickets"><section className="panel"><div className="row"><div><h2>Guest list</h2><p>Create tickets after receiving payment.</p></div><div className="actions"><button className="secondary" aria-label="Refresh guest list" onClick={()=>void refresh()}><RefreshCw size={18}/></button><button className="primary" onClick={start}><Plus size={18}/> New ticket</button></div></div>{!ev.gate_key&&<p className="message">Set the date, venue and price in the Event tab before creating tickets.</p>}<label className="muted">Find a guest<input className="search" placeholder="Name, contact or ticket ID" value={query} onChange={e=>setQuery(e.target.value)}/></label>{!tickets.length?<div className="empty"><Ticket size={36}/><h3>Your celebration starts here</h3><p>Your paid guests and their entry status will appear here.</p></div>:<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Guest</TableHead><TableHead>Payment</TableHead><TableHead>Entry</TableHead><TableHead>Ticket</TableHead></TableRow></TableHeader><TableBody>{visible.map(t=><TableRow key={t.token}><TableCell><strong>{t.name}</strong><div className="muted">{t.contact}</div><div className="muted">{t.token.slice(0,8).toUpperCase()}</div></TableCell><TableCell>₹{(t.amount/100).toLocaleString('en-IN')}<div className="muted">{t.method}</div></TableCell><TableCell><span className="badge">{t.cancelled?'Cancelled':t.entered_at?'Checked in':'Not entered'}</span>{t.entered_at&&<div className="muted">{new Date(t.entered_at).toLocaleTimeString('en-IN')} · {t.receipt}</div>}</TableCell><TableCell><div className="actions"><a className="small-btn" target="_blank" rel="noreferrer" href={'/t/'+t.token}>View</a><button className="small-btn" onClick={()=>void copy(t)}>Copy link</button>{!t.cancelled&&!t.entered_at&&<button className="small-btn" onClick={()=>setConfirm(t)}>Cancel</button>}</div></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<p>No matching guests.</p>}</div>}</section></TabsContent>
 <TabsContent value="gate"><div className="grid2"><section className="panel"><div className="no-print"><h2>Master gate QR</h2><p>Print this poster and place it beside the gate volunteer. Guests scan it from their personal ticket page.</p></div><h2 style={{textAlign:'center'}}>{ev.name}</h2>{qr?<img src={qr} className="qr" alt="Master entrance QR code"/>:<p>Save your event details to create the QR.</p>}<h3 style={{textAlign:'center'}}>Open your ticket. Scan here.</h3><p style={{textAlign:'center'}}>Show the result to the gate volunteer.</p><button className="secondary no-print" disabled={!qr} onClick={()=>window.print()}><Printer size={16} style={{display:'inline',marginRight:8}}/> Print gate poster</button></section><section className="panel no-print stack"><div><h2>Gate is {ev.gate_open?'open':'closed'}</h2><p>{ev.gate_open?'Guests can check in now.':'Guests cannot check in until you open the gate.'}</p><button className="primary" disabled={busy||!ev.gate_key} onClick={()=>void run(async()=>{await call({action:'gate',open:!ev.gate_open});await refresh(true)})}>{ev.gate_open?'Close entry':'Open entry'}</button></div><div><h3>Volunteer check</h3><p>Watch the guest scan. Match their name and entry receipt against the live guest list. A screenshot alone is not proof of a fresh entry.</p><p className="muted">A printed QR can be shared. Keep entry closed until the event and have a volunteer supervise each admission. Internet is required.</p></div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const raw=String(f.get('token')).trim();const token=raw.includes('/t/')?raw.split('/t/')[1].split(/[?#]/)[0]:raw;const r=await call({action:'admit',token});setMessage('Admitted: '+r.ticket.name+' · receipt '+r.ticket.receipt);await refresh(true)})}}><h3>Camera not working?</h3><label>Guest's full ticket ID or link<input name="token" required placeholder="Paste the guest's ticket link"/></label><button className="secondary" disabled={busy||!ev.gate_open}>Confirm entry for this guest</button></form><h3>Latest entries</h3>{checked.slice().sort((a,b)=>(b.entered_at||'').localeCompare(a.entered_at||'')).slice(0,8).map(t=><div key={t.token}><strong>{t.name}</strong><div className="muted">{t.receipt} · {new Date(t.entered_at!).toLocaleTimeString('en-IN')}</div></div>)}</section></div></TabsContent>
 <TabsContent value="team"><section className="panel stack"><div><h2>Your five-person team</h2><p>Everyone can issue tickets and manage the gate. Only the owner can change event details and team access.</p><p className="muted">Signed in as {data.user.email}{data.user.isOwner?' · Owner':''}</p></div>{data.user.isOwner?<><div className="row"><strong>{data.user.email}</strong><span className="badge">Owner</span></div>{data.team.map(m=><div className="row" key={m.email}><span>{m.email}</span><button disabled={busy} className="small-btn" onClick={()=>void run(async()=>{await call({action:'member',email:m.email,remove:true});await refresh(true)})}>Remove access</button></div>)}<form className="form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;const email=new FormData(f).get('email');void run(async()=>{await call({action:'member',email});await refresh(true);f.reset();setMessage('Teammate added.')})}}><label>Teammate email<input required type="email" name="email" placeholder="friend@example.com"/></label><button className="primary" disabled={busy||data.team.length>=4}>Add teammate ({data.team.length}/4)</button></form><p className="muted">Adding an email grants dashboard access; it does not send a message or invitation.</p></>:<p>Ask your event owner to add or remove teammates.</p>}</section></TabsContent>
 <TabsContent value="event"><section className="panel"><h2>Make it your night</h2><p>These details appear on every ticket. Times are in India Standard Time.</p><form className="form" onSubmit={e=>{e.preventDefault();void run(async()=>{await call({action:'event',...form});await refresh(true);setMessage('Event details saved.')})}}><label>Event name<input value={form.name} maxLength={80} required disabled={!data.user.isOwner} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date and time (IST)<input type="datetime-local" value={form.date} required disabled={!data.user.isOwner} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Venue and address<input value={form.venue} maxLength={200} required disabled={!data.user.isOwner} onChange={e=>setForm({...form,venue:e.target.value})}/></label><label>Ticket price (₹)<input type="number" min="0" max="100000" step="0.01" value={form.price} required disabled={!data.user.isOwner} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><p className="muted">Payments are collected separately. Price changes apply to newly issued tickets.</p>{data.user.isOwner&&<button disabled={busy} className="primary">Save event details</button>}</form></section></TabsContent>
 </Tabs>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogTitle>{newTicket?'Ready for the celebration':'Create a paid ticket'}</DialogTitle><DialogDescription>{newTicket?'Send this personal ticket link to your guest.':'One guest, one ticket. Issue only after receiving payment.'}</DialogDescription>{error&&<div role="alert" className="message">{error}</div>}{newTicket?<div className="stack"><h3>{newTicket.name}</h3><input aria-label="Ticket link" className="search" readOnly value={typeof window!=='undefined'?link(newTicket):''} onFocus={e=>e.target.select()}/><div className="actions"><button className="primary" onClick={()=>void copy(newTicket)}><Copy size={16}/> Copy link</button><a className="secondary" href={'/t/'+newTicket.token} target="_blank" rel="noreferrer">View ticket</a><a className="secondary" target="_blank" rel="noreferrer" href={'https://wa.me/?text='+encodeURIComponent('Your '+ev.name+' ticket for '+newTicket.name+': '+(typeof window!=='undefined'?link(newTicket):''))}>Share on WhatsApp</a></div><p className="muted">Keep the ticket link private. It grants entry once.</p></div>:<form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const r=await call({action:'issue',name:f.get('name'),contact:f.get('contact'),paid,method,requestId});setNewTicket(r.ticket);await refresh(true)})}}><label>Guest name<input required name="name" maxLength={100} autoComplete="name"/></label><label>Phone or contact (optional)<input name="contact" maxLength={100}/></label><label>Payment received by<Select value={method} onValueChange={setMethod}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{['Cash','UPI / personal transfer','Other'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><p>Ticket amount: <strong>₹{(ev.price/100).toLocaleString('en-IN')}</strong></p><div className="actions"><Checkbox id="paid" checked={paid} onCheckedChange={v=>setPaid(v===true)}/><label htmlFor="paid">I have received the full payment.</label></div><button className="primary" disabled={busy||!paid||!ev.gate_key}>{busy?'Creating…':'Create ticket'}</button></form>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!confirm)setConfirm(null)}}><AlertDialogContent><AlertDialogTitle>Cancel this ticket?</AlertDialogTitle><AlertDialogDescription>{confirm?.name} will no longer be able to enter with this ticket. Handle any refund separately.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep ticket</AlertDialogCancel><AlertDialogAction onClick={()=>{const t=confirm;if(t)void run(async()=>{await call({action:'cancel',token:t.token});await refresh(true)})}}>Cancel ticket</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
